/version: '3'
services:
  web: 
    build: ./docker/web
    volumes:
      - ./:/var/www/html/
    
    ports:
      - 80:80

  db: 
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=xamp
      - MYSQL_USER=xamp
      - MYSQL_PASSWORD=mypassword
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  db:
